services:
    phpbbservices.notifyonerror.common:
        class: phpbbservices\notifyonerror\core\common
        arguments:
            - '@config'
    phpbbservices.notifyonerror.listener:
        class: phpbbservices\notifyonerror\event\main_listener
        arguments:
            - '@config'
            - '@notification_manager'
            - '@phpbbservices.notifyonerror.common'
            - '@user'
        tags:
            - { name: event.listener }
    phpbbservices.notifyonerror.notification.type.errorlog:
        class: phpbbservices\notifyonerror\notification\type\errorlog
        shared: false
        parent: notification.type.base
        tags:
            - { name: notification.type }